#
# Vagrantfile to create Hands on Lab
#
# Copyright (c) 2020 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl
#
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Memory for the VMs (2GB)
  MEMORY = 2048

  GROUP = "/NBDE-lab"

  # Box metadata location and box name
  BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
  BOX_NAME = "oraclelinux/8"

  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"

  config.vm.provider :virtualbox do |vb|
    vb.memory = MEMORY
    vb.customize ["modifyvm", :id, "--groups", GROUP] unless GROUP.nil?
  end

  config.vagrant.plugins = "vagrant-hosts"

  if Vagrant.has_plugin?("vagrant-hosts")
    config.vm.provision :hosts do |provisioner|
      provisioner.add_localhost_hostnames = false
      provisioner.sync_hosts = true
      provisioner.autoconfigure = true
    end
  end

  # Vagrant box has firewall disabled but standard Oracle Linux 8 will not.
  config.vm.provision "shell",
    inline: "systemctl enable --now firewalld"

  config.vm.define "keyserver" do |keyserver|
    keyserver.vm.hostname = "keyserver.vagrant.vm"
    keyserver.vm.network "private_network",  ip: "192.168.99.200"
  end

  config.vm.define "appserver" do |appserver|
    appserver.vm.hostname = "appserver.vagrant.vm"
    appserver.vm.network "private_network", ip: "192.168.99.201"
  end

  config.vm.post_up_message = "Build complete"
end
